// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGCyUiljuWxqBHU4W1siIb5afl4HI0xp0',
    appId: '1:1056657376988:web:79bc8c90e9aefbda3d9619',
    messagingSenderId: '1056657376988',
    projectId: 'stamina-check-list',
    authDomain: 'stamina-check-list.firebaseapp.com',
    storageBucket: 'stamina-check-list.firebasestorage.app',
    measurementId: 'G-FTBP0999LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCampLF5VToiQoLOKsNImfKg0RYUW2LD4w',
    appId: '1:1056657376988:android:f5075d309c6ba3bf3d9619',
    messagingSenderId: '1056657376988',
    projectId: 'stamina-check-list',
    storageBucket: 'stamina-check-list.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxbvWoRCg1KJRbK5Ume_Ak1QtVKJ6Uckg',
    appId: '1:1056657376988:ios:178b6555d426a6b03d9619',
    messagingSenderId: '1056657376988',
    projectId: 'stamina-check-list',
    storageBucket: 'stamina-check-list.firebasestorage.app',
    iosBundleId: 'com.example.staminaCheckList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxbvWoRCg1KJRbK5Ume_Ak1QtVKJ6Uckg',
    appId: '1:1056657376988:ios:178b6555d426a6b03d9619',
    messagingSenderId: '1056657376988',
    projectId: 'stamina-check-list',
    storageBucket: 'stamina-check-list.firebasestorage.app',
    iosBundleId: 'com.example.staminaCheckList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGCyUiljuWxqBHU4W1siIb5afl4HI0xp0',
    appId: '1:1056657376988:web:4590c00e4b95eb553d9619',
    messagingSenderId: '1056657376988',
    projectId: 'stamina-check-list',
    authDomain: 'stamina-check-list.firebaseapp.com',
    storageBucket: 'stamina-check-list.firebasestorage.app',
    measurementId: 'G-7K4JTYPT18',
  );
}
